<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_options_payments-index');?>">Způsob platby</a>  &#62; </li>
	  <li>Přidat způsob platby</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="payment" class="first active">Přidat způsob platby</li>
	  <li id="settings" class="last disable">Nastavení</li>
	  <li class="line" style="width: 525px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formPayments;?>
	</div>
	<div id="tab2">
	</div>
</div>