<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_products_products-index');?>">Přehled zboží</a>  &#62; </li>
	  <li>Smazat zboží</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="users" class="first active last">Smazat zboží</li>
	  <li class="line" style="width: 632px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h2 class="text-center">Opravdu chcete smazat zboží "<?= $this->product;?>"?</h2>
		<?= $this->form;?>
	</div>
</div>