<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_products_products-index');?>">Přehled zboží</a>  &#62; </li>
	  <li>Editovat zboží</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active">Upravit zboží</li>
	  <li id="categories">Kategorie</li>
	  <li id="pictures">Obrázky</li>
	  <li id="parameters">Paramerty</li>
	  <li id="settings" class="last">Nastavení</li>
	  <li class="line" style="width: 371px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formProduct;?>
	</div>
	<div id="tab2">
		<?= $this->formCategories;?>
	</div>
	<div id="tab3">
		<?= $this->formPics;?>
		
		<?php if ($this->pics){?>
			<div id="pics-box">
				<?php $i=1;?>
				<?php foreach ($this->pics as $pic) {?>
					<div id="pic"<?= (($i % 6)==0)?' class="last"':'';?>>
						<img src="/<?= $pic['100x100'];?>" />
						<div class="<?= ($pic['active'])?'':'no';?>active">
							<a href="<?= $this->url(array(
									'product_id'	=>	$this->product_id,
									'id'			=>	$pic['id']
								),'admin_products_products-active');?>" rel="nofollow"></a>
						</div>
						<?php if ($i>1){?>
							<div class="left">
								<a href="<?= $this->url(array(
										'product_id'	=>	$this->product_id,
										'id'			=>	$pic['id']
									),'admin_products_products-move-left');?>" rel="nofollow"></a>
							</div>
						<?php }?>
						<?php if ($i<count($this->pics)){?>
							<div class="right">
								<a href="<?= $this->url(array(
										'product_id'	=>	$this->product_id,
										'id'			=>	$pic['id']
									),'admin_products_products-move-right');?>" rel="nofollow"></a>
							</div>
						<?php }?>
						<div class="delete">
							<a href="<?= $this->url(array(
									'product_id'	=>	$this->product_id,
									'id'			=>	$pic['id']
								),'admin_products_products-del-picture');?>" rel="nofollow"></a>
						</div>
					</div>
					<?php $i++;?>
				<?php }?>
				<div class="floatfix"></div>
			</div>
		<?php }?>
	</div>
	<div id="tab4">
		<nav id="form-tab-menu">
			<ul>
			  <li id="parameter" class="first active">Přidat parametr</li>
			  <li id="parameters-group" class="last">Přidat skupinu parametrů</li>
			  <li class="line" style="width: 420px;"></li>
			</ul>
		</nav>
		<div id="form-tab-box">
			<div id="tab4-1">
				<?= $this->formParameters;?>
			</div>
			<div id="tab4-2">
				<?= $this->formParametersGroup;?>
			</div>
		</div>
		<table>
			<thead>
				<tr>
					<th>Parametry</th>
					<th>Hodnota</th>
					<th class="width-40">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->parameters){?>
					<?php for ($i = 0; $i < count($this->parameters); $i++) {?>
						<tr>
							<td><?= $this->parameters[$i]['title']?></td>
							<td><?= $this->parameters[$i]['value'];?></td>
							<td><span><a class="delete" href="<?= $this->url(array(
									'id'		=>	$this->product_id,
									'back'		=>	2,
									'param_id'	=> $this->parameters[$i]['id']
								),'admin_products_products_parameter-del');?>" title="Smazat"></a></span></td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyl přidán žádný parametr</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
		
	</div>
	<div id="tab5">
		<?= $this->formSettings;?>
	</div>
</div>