<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a> &#62; </li>
	  <li>Přehled zboží</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active last">Přehled zboží</li>
	  <li class="line" style="width: 632px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_products_products-add');?>"><span class="add-item"></span>Přidat zboží</a>
		<?= $this->searchForm;?>
		<?= ($this->paginator)?$this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml'):NULL; ?>
		<table>
			<thead>
				<tr>
					<th>Kód</th>
					<th>Zboží</th>
					<th>URL adresa</th>
					<th class="width-30"><span class="help" title="Počet kategorii"></span></th>
					<th class="width-30"><span class="help" title="Kategorie"></span></th>
					<th class="width-30"><span class="help" title="Zobrazen"></span></th>
					<th class="width-30"><span class="help" title="Doporučen"></span></th>
					<th class="width-30"><span class="help" title="Novinka"></span></th>
					<th class="width-30">&nbsp;</th>
					<th class="width-30">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->products){?>
					<?php for ($i = 0; $i < count($this->products); $i++) {?>
						<tr>
							<td><?= $this->products[$i]['code']?></td>
							<td><?= $this->products[$i]['title_menu']?></td>
							<td><?= $this->products[$i]['title_url']?></td>
							<td class="text-center">
								<?= ($this->products[$i]['categories_count']>0)?$this->products[$i]['categories_count']:'';?>
							</td>
							<td>
								<span class="<?= ($this->products[$i]['categories_count']>0)?'check':'uncheck';?>"
									  title="<?= ($this->products[$i]['categories_count']>0)?'Zařazeno':'Nezařazeno';?>">
								</span>
							</td>
							<td>
								<span class="<?= ($this->products[$i]['show'])?'check':'uncheck';?>"
									  title="<?= ($this->products[$i]['show'])?'Zobrazen':'Nezobrazen';?>">
								</span>
							</td>
							<td>
								<span class="<?= ($this->products[$i]['recommend'])?'check':'uncheck';?>"
									  title="<?= ($this->products[$i]['recommend'])?'Zobrazen':'Nezobrazen';?>">
								</span>
							</td>
							<td>
								<span class="<?= ($this->products[$i]['news'])?'check':'uncheck';?>"
									  title="<?= ($this->products[$i]['news'])?'Zobrazen':'Nezobrazen';?>">
								</span>
							</td>
							<td>
								<span class="detail">
									<a href="<?= $this->url(array('id'=>$this->products[$i]['id']),'admin_products_products-edit');?>"
									   title="Upravit"></a>
								</span>
							</td>
							<td>
								<span class="delete">
									<a href="<?= $this->url(array('id'=>$this->products[$i]['id']),'admin_products_products-del');?>"
									   title="Smazat"></a>
								</span>
							</td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebylo přidáno žádné zboží</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<th>&nbsp;</th>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
		<?= ($this->paginator)?$this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml'):NULL; ?>
	</div>
</div>