[production]

; AUTH ********************************************************************************************
routes.auth_index_my-account.route = "/muj-ucet"
routes.auth_index_my-account.defaults.module = auth
routes.auth_index_my-account.defaults.controller = index
routes.auth_index_my-account.defaults.action = my-account

routes.auth_index_login.route = "/muj-ucet/prihlaseni"
routes.auth_index_login.defaults.module = auth
routes.auth_index_login.defaults.controller = index
routes.auth_index_login.defaults.action = login

routes.auth_index_logout.route = "/muj-ucet/odhlaseni"
routes.auth_index_logout.defaults.module = auth
routes.auth_index_logout.defaults.controller = index
routes.auth_index_logout.defaults.action = logout

routes.auth_index_registration.route = "/muj-ucet/registrace"
routes.auth_index_registration.defaults.module = auth
routes.auth_index_registration.defaults.controller = index
routes.auth_index_registration.defaults.action = registration

routes.auth_index_registration-continue.route = "/muj-ucet/registrace/token/:token"
routes.auth_index_registration-continue.defaults.module = auth
routes.auth_index_registration-continue.defaults.controller = index
routes.auth_index_registration-continue.defaults.action = registration-continue
routes.auth_index_registration-continue.defaults.token = ""
routes.auth_index_registration-continue.reqs.token = "\w+"

routes.auth_index_registration-done.route = "/muj-ucet/registrace/dokoncena"
routes.auth_index_registration-done.defaults.module = auth
routes.auth_index_registration-done.defaults.controller = index
routes.auth_index_registration-done.defaults.action = registration-done

routes.auth_index_password-change.route = "/muj-ucet/zmena-hesla"
routes.auth_index_password-change.defaults.module = auth
routes.auth_index_password-change.defaults.controller = index
routes.auth_index_password-change.defaults.action = password-change

routes.auth_index_password-changed.route = "/muj-ucet/zmena-hesla/dokonceno"
routes.auth_index_password-changed.defaults.module = auth
routes.auth_index_password-changed.defaults.controller = index
routes.auth_index_password-changed.defaults.action = password-changed

routes.auth_index_password-generated.route = "/muj-ucet/zapomenute-heslo/dokonceno"
routes.auth_index_password-generated.defaults.module = auth
routes.auth_index_password-generated.defaults.controller = index
routes.auth_index_password-generated.defaults.action = password-generated
;**************************************************************************************************

; PROFILE *****************************************************************************************
routes.auth_profile_edit.route = "/muj-ucet/profil/editace"
routes.auth_profile_edit.defaults.module = auth
routes.auth_profile_edit.defaults.controller = profile
routes.auth_profile_edit.defaults.action = edit
;**************************************************************************************************

; ADDRESS *****************************************************************************************
routes.auth_address_index.route = "/muj-ucet/profil/adresy"
routes.auth_address_index.defaults.module = auth
routes.auth_address_index.defaults.controller = address
routes.auth_address_index.defaults.action = index

routes.auth_address_add.route = "/muj-ucet/profil/adresy/pridat"
routes.auth_address_add.defaults.module = auth
routes.auth_address_add.defaults.controller = address
routes.auth_address_add.defaults.action = add

routes.auth_address_del.route = "/muj-ucet/profil/adresy/smazat/:id"
routes.auth_address_del.defaults.module = auth
routes.auth_address_del.defaults.controller = address
routes.auth_address_del.defaults.action = del
routes.auth_address_del.defaults.id = 0
routes.auth_address_del.reqs.id = "\d+"
;**************************************************************************************************