<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li>O produktu</li>
	</ul>
</nav>

<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Verze 0.5 beta</li>
	  <li class="line" style="width: 624px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h3>Objednávky</h3>
		<ul>
			<li>Přidána funkce vytváření objednávky ve formátu PDF</li>
			<li>Přidána funkce "Nové objednávky". Nyní se nové objednávky zobrazují na hlavní stránce v sekci "Admin"</li>
		</ul>
		<h3>Zboží</h3>
		<ul>
			<li>Přidána podpora skupin parametrů pro parametry zboží. Nyní je možno hromadně přídávat parametry ke zboží</li>
			<li>Přidána podpora vkládání obrázků zboží ve formátu *.jpg, *.gif, *.png</li>
			<li>Přidána podpora automatického generování kódu zboží. Nyní není nutno zadávat kód zboží</li>
		</ul>
		<h3>Nastavení eshopu</h3>
		<ul>
			<li>Přidána podpora dopravného</li>
			<li>Přidána podpora doběrečného. Nyní je možno zasílat zboží na dobírku</li>
			<li>Přidány informace o registraci firmy</li>
			<li>Přidány informace o bance. Tyto informace se zobrazují v přijatých objednávkách</li>
			<li>Přidána podpora měny v eshopu</li>
		</ul>
	</div>
</div>