<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li>Nastavení eshopu</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="eshop" class="first active">eShop</li>
	  <li id="currency">Měna</li>
	  <li id="smtp">SMTP</li>
	  <li id="bank">Banka</li>
	  <li id="company" class="last">Firma</li>
	  <li class="line" style="width: 499px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->eshopForm;?>
	</div>
	<div id="tab2">
		<?= $this->currencyForm;?>
	</div>
	<div id="tab3">
		<?= $this->smtpForm;?>
	</div>
	<div id="tab4">
		<?= $this->bankForm;?>
	</div>
	<div id="tab5">
		<?= $this->companyForm;?>
	</div>
</div>