<section class="contact">
	<img class="contact" src="/img/layout/contact.png" />
	<section class="address">
		<h2>Kontakty:</h2>
		<ul class="address">
			<li>Partyzánské nám.5</li>
			<li>Ostrava</li>
			<li>702 00</li>
			<li>Czech Republic</li>
		</ul> 
		<ul class="right">
			<li>www.KREZBO.cz</li>
			<li>krezbo@krezbo.cz</li>
		</ul>
		<ul class="left">
			<li>IČ: 46534792</li>
			<li>DIČ: CZ6209281859</li>
		</ul>
		<ul class="phones">
			<li>Fax : +420 596 122 101</li>
		</ul>
		<ul class="person-left" style="margin-top: 40px;">
		  <li>Zdeněk Zbořil</li>
		  <li>z.zboril@krezbo.cz</li>

		</ul>
		<ul class="person-right" style="margin-top: 40px;">
            <li>Tel.: 596 122 101</li>
            <li>Mob.: 602 795 007</li>
		</ul>
		<ul class="opening-hours">
		  <li>Prodejní doba:</li>
		  <li><span>Pondělí:</span>8:30 až 12:00, 13:00 až 16:00</li>
		  <li><span>Úterý:</span>8:30 až 12:00, 13:00 až 16:00</li>
		  <li><span>Středa:</span>8:30 až 12:00, 13:00 až 16:00</li>
		  <li><span>Čtvrtek:</span>8:30 až 12:00, 13:00 až 16:00</li>
		  <li><span>Pátek:</span>8:30 až 12:00, 13:00 až 16:00</li>
		  <li><span>Sobota:</span>Zavřeno</li>
		  <li><span>Neděle:</span>Zavřeno</li>
		</ul>
	</section>
</section>