<section class="gallery">
	<h1>Galerie</h1>
	<h2>Naše provozovna:</h2>
	<ul>
		<li>
			<a href="/data/gallery/800x600/gallery001_1.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_1.jpg" />
			</a>
		</li>	
		<li>
			<a href="/data/gallery/800x600/gallery001_2.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_2.jpg" />
			</a>
		</li>	
		<li>
			<a href="/data/gallery/800x600/gallery001_3.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_3.jpg" />
			</a>
		</li>	
		<li>
			<a href="/data/gallery/800x600/gallery001_4.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_4.jpg" />
			</a>
		</li>	
		<li>
			<a href="/data/gallery/800x600/gallery001_5.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_5.jpg" />
			</a>
		</li>	
		<li>
			<a href="/data/gallery/800x600/gallery001_6.jpg" rel="prettyPhoto[gallery1]">
				<img src="/data/gallery/160x120/gallery001_6.jpg" />
			</a>
		</li>	
		
	</ul>
	<div class="clearfix"></div>
</section>