<section class="about-us">
	<a href="http://www.eshop.krezbo.cz">
		<img class="eshop" src="/img/layout/eshop.png" />
	</a>
	<div class="about-us-box">
		<div class="right-box">
			<h1>O nás</h1>
			<h2>Nabízíme prodej:</h2>
			<nav>
				<ul>
					<li>čerpadel</li>
					<li>domácích vodáren</li>
					<li>ručních pump</li>
					<li>zahradních hadic</li>
					<li>náhradních dílů k čerpadlum i vodárnám</li>
				</ul>
			</nav>
			<h3>v rámci maloobchodu i velkoobchodu</h3>
		</div>
		<div class="left-box">
			<h2>Dále nabízíme:</h2>
			<nav>
				<ul>
					<li>teplovodní techniku včetně regulace a spojovacího materiálu (fitinky)</li>
					<li>montáže domácích vodáren</li>
					<li>Součástí naší nabídky je i poradenská služba a servis.</li>
				</ul>
			</nav>
		</div>
	</div>
	
	<div class="box">
		<h2>Zastoupeni firem:</h2>
		<a class="logo sigma" rel="nofollow" target="_blank" title="Sigmagroup" href="http://www.sigmagroup.cz/"></a>
		<a class="logo komextherm" rel="nofollow" target="_blank" title="Komextherm Praha" href="http://www.komextherm.cz/"></a>
		<a class="logo metra" rel="nofollow" target="_blank" title="Metra Šumperk" href="http://www.metra-su.cz/"></a>
		<a class="logo grundfos" rel="nofollow" target="_blank" title="Grundfos" href="http://www.grundfos.com/"></a>
		<a class="logo espa" rel="nofollow" target="_blank" title="" href="http://www.espa.com/"></a>
		<a class="logo kopro" rel="nofollow" target="_blank" title="Kopro" href="http://www.kopro.cz/"></a>
		<a class="logo wilo" rel="nofollow" target="_blank" title="Wilo Praha s.r.o." href="http://www.wilo.cz/"></a>
		<a class="logo alfapumpy" rel="nofollow" target="_blank" title="Alfapumpy" href="http://www.alfapumpy.cz/"></a>
		<a class="logo aquatrading" rel="nofollow" target="_blank" title="Aquatrading" href="http://www.aquatradingpumps.cz/"></a>
		<a class="logo aqua-cup" rel="nofollow" target="_blank" title="Aquacup" href="http://www.aquacup.cz/"></a>
		<a class="logo flygt" rel="nofollow" target="_blank" title="Flygt" href="http://www.flygt.com/"></a>
	</div>
	
</section>