<section class="request">
	<img class="contact" src="/img/layout/contact.png" />
	<div style="text-align: center;">
		<h1>Poslat poptávku</h1>
	    Pokud nám chcete zaslat poptávku, využijte prosím tento formulář.<br />
		Na Vaši žádost Vám velmi ochotně zašleme materiály poštou,<br />
		nebo můžete navrhnout termín schůzky pro upřesnění Vašich požadavků.<br /><br />
	</div>
	<?= $this->form;?>
</section>