<section class="sitemap">
	<ul>
		<li><a href="<?= $this->url(array(),'default_index_index');?>">O nás</a></li>
		<li><a href="<?= $this->url(array(),'default_index_request');?>">Poptávka</a></li>
		<li><a href="<?= $this->url(array(),'default_index_gallery');?>">Galerie</a></li>
		<li><a href="<?= $this->url(array(),'default_index_contact');?>">Kontakt</a></li>
		<li><a href="http://www.eshop.krezbo.cz/">eShop</a></li>
		<li><a href="<?= $this->url(array(),'default_index_sitemap');?>">Mapa webu</a></li>
	</ul>
</section>