<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li>Vodoznak</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="watermark" class="first active">Vodoznak</li>
	  <li id="load">Změnit vodoznak</li>
	  <li id="settings" class="last">Nastavení</li>
	  <li class="line" style="width: 475px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<img class="watermark" src="/data/png/watermark/watermark.png" />
	</div>
	<div id="tab2">
		<?= $this->formWatermark;?>
	</div>
	<div id="tab3">
		<?= $this->formSettings;?>
	</div>
</div>