<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_elements');?>">Prvky stránek</a> &#62; </li>
	  <li>Rychlý kontakt</li>
	</ul>
</nav>
<section class="quick-contact">
	<div class="clearfix"></div>
	<nav id="form-tab-menu">
		<ul>
		  <li id="payment" class="first active last">Rychlý kontakt</li>
		  <li class="line" style="width: 623px;"></li>
		</ul>
	</nav>
	<div id="form-tab-box">
		<div id="tab1">
			<?= $this->form;?>
		</div>
	</div>
</section>