<div class="block">

	<h1 class="address">Adresy</h1>
	<nav id="options">
		<ul>
			<li>Přihlášení uživatele
				<ul>
					<li>Pro dokončení objednávky není nutné být registrován a přihlášen. Doporučujeme Vám ale registraci provést a využívat tak množství <span class="services">služeb</span> poskytovaných registrovaným zákazníkům.
						<!--<ul id="services">
							<li>nastavovat a upravovat údaje související s Vaši registrací</li>
							<li>nastavovat fakturační a dodací adresy pro objednávky</li>
							<li>sledovat všechny Vaše objednávky a jejich stav vyřízení</li>
							<li>mít přehled o speciálních slevách a akcích</li>
							<li>odebírat Novinky</li>
						</ul>  -->
					</li>
					<li>Chcete-li se přihlásit, vyplňte prosím přihlašovací údaje v panelu <span class="login-registration">Přihlášení</span>.</li>
					<li>Nejste-li v internetovém obchodě ještě registrováni, můžete toto provést v panelu <span class="login-registration">Registrace</span>.</li>
				</ul>
			</li>
		</ul>
	</nav>
	<div class="clearfix"></div>
	<?= $this->UAform;?>
	<?= $this->form;?>

</div>