<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_marketing');?>">Marketing</a> &#62; </li>
	  <li>Export</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Export</li>
	  <li class="line" style="width: 671px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a class="button" href="<?= $this->url(array(),'admin_marketing_export-zbozicz');?>">Export pro Zboží.cz</a>
		<a class="button" href="<?= $this->url(array(),'admin_marketing_export-sitemap');?>">Exportovat Sitemap</a>
	</div>
</div>