<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_products_vat-index');?>">Přehled DPH</a>  &gt; </li>
	  <li>Smazat DPH</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="vat" class="first active last">Smazat DPH</li>
	  <li class="line" style="width: 637px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h2 class="text-center">Opravdu chcete smazat DPH "<?= $this->vat;?>"?</h2>
		<?= $this->form;?>
	</div>
</div>