<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_products_parameters-index');?>">Přehled parametrů</a>  &gt; </li>
	  <li>Smazat skupinu</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="parameter" class="first active last">Smazat skupinu parametrů</li>
	  <li class="line" style="width: 553px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h2 class="text-center">Opravdu chcete smazat skupinu parametrů "<?= $this->group;?>"?</h2>
		<?= $this->form;?>
	</div>
</div>