<div style="clear:both !important;"></div>
	
<aside id="quick-contact">
	<div id="quick-contact-bar">
		<ul class="aside-right">
			<li class="top"></li>
			<li class="middle"></li>
			<li class="bottom"></li>
		</ul>
	</div>
	<div id="quick-contact-box" class="aside-right-box">
		<h1>Rychlý kontakt</h1>
		<h1><?= $this->quickContactEmail;?></h1>
		<a href="<?= $this->url(array(),'quick-contact_eshop_index');?>">Kontaktovat</a>
	</div>
</aside>

<div style="clear:both !important;"></div>