<?= $this->doctype() . "\n";?>
<html lang="cs" dir="ltr">
<head>
<?= $this->headMeta() . "\n";?>
<?= $this->headTitle() . "\n";?>
<?= $this->headLink() . "\n";?>
<?= $this->headStyle();?>
<?= $this->jQuery();?>
<?= $this->headScript() . "\n";?>
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="company-logo"><h1><a href="<?= $this->url(array(),'default_index_index');?>">Krezbo</a></h1></div>
			<nav class="company-menu">
				<ul>
					<li><a href="<?= $this->url(array(),'default_index_index');?>">O nás</a></li>
					<li><a href="<?= $this->url(array(),'default_index_request');?>">Poptávka</a></li>
					<li><a href="<?= $this->url(array(),'default_index_gallery');?>">Galerie</a></li>
					<li><a href="<?= $this->url(array(),'default_index_contact');?>">Kontakt</a></li>
					<li><a href="http://www.eshop.krezbo.cz/">eShop</a></li>
				</ul>
			</nav>
		</header>
		
		<article>
			<?= $this->layout()->content;?>
		</article>
	</div>
	<div class="clearfix"></div>
	<footer>
		<div class="wrapper">
			<a class="sitemap" href="<?= $this->url(array(),'default_index_sitemap');?>">Mapa webu</a>
			KREZBO &copy; <?= date('Y');?> Všechna práva vyhrazena
			<a class="logo" href="http://www.bvdesign.cz" title="be Visible Design"></a>
		</div>
	</footer>
	<?php if (APPLICATION_ENV == 'production') {?>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-5141258-10']);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script');
			ga.type = 'text/javascript';
			ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(ga, s);
		})();
	</script>
	<?php }?>
</body>
</html>