<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_options_countries-index');?>">Přehled zemí</a>  &#62; </li>
	  <li>Přidat zemi</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="country" class="first active">Přidat zemi</li>
	  <li id="settings" class="last disable">Nastavení</li>
	  <li class="line" style="width: 577px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formCountries;?>
	</div>
	<div id="tab2">
	</div>
</div>