<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_options_countries-index');?>">Přehled zemí</a>  &#62; </li>
	  <li>Smazat zemi</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="users" class="first active last">Smazat zemi</li>
	  <li class="line" style="width: 634px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h2 class="text-center">Opravdu chcete smazat zemi "<?= $this->country;?>"?</h2>
		<?= $this->form;?>
	</div>
</div>