<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li>Přehled zemí</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Přehled zemí</li>
	  <li class="line" style="width: 634px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_options_countries-add');?>"><span class="add-item"></span>Přidat zemi</a>
		<div class="clearfix"></div>
		<table>
			<thead>
				<tr>
					<th>Země</th>
					<th class="width-80">Zobrazen</th>
					<th class="width-40">&nbsp;</th>
					<th class="width-40">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->countries){?>
					<?php for ($i = 0; $i < count($this->countries); $i++) {?>
						<tr>
							<td><?= $this->countries[$i]['country']?></td>
							<td><span class="<?= ($this->countries[$i]['show'])?'check':'uncheck';?>" title="<?= ($this->countries[$i]['show'])?'Zobrazen':'Nezobrazen';?>">&nbsp;</span></td>
							<td><span class="detail"><a href="<?= $this->url(array('id'=>$this->countries[$i]['id']),'admin_options_countries-edit');?>" title="Upravit"></a></span></td>
							<td><span class="delete"><a href="<?= $this->url(array('id'=>$this->countries[$i]['id']),'admin_options_countries-del');?>" title="Smazat"></a></span></td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyl přidána žádná země</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>