<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_options_consumptions-index');?>">Způsob odběru</a>  &#62; </li>
	  <li>Upravit způsob odberu</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="consumptions" class="first active">Upravit způsob odberu</li>
	  <li id="settings" class="last">Nastavení</li>
	  <li class="line" style="width: 512px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formConsumptions;?>
	</div>
	<div id="tab2">
		<?= $this->formSettings;?>
	</div>
</div>