<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_options');?>">Nastavení</a>  &#62; </li>
	  <li>Způsob odběru</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Způsoby odběru</li>
	  <li class="line" style="width: 615px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_options_consumptions-add');?>"><span class="add-item"></span>Přidat způsob odběru</a>
		<div class="clearfix"></div>
		<table>
			<thead>
				<tr>
					<th>Způsob odběru</th>
					<th>Cena s DPH</th>
					<th class="width-80">Zobrazen</th>
					<th class="width-40">&nbsp;</th>
					<th class="width-40">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->consumptions){?>
					<?php for ($i = 0; $i < count($this->consumptions); $i++) {?>
						<tr>
							<td><?= $this->consumptions[$i]['consumption'];?></td>
							<td><?= $this->consumptions[$i]['price'].(($this->consumptions[$i]['price'])?' '.$this->currency:'');?></td>
							<td><span class="<?= ($this->consumptions[$i]['show'])?'check':'uncheck';?>" title="<?= ($this->consumptions[$i]['show'])?'Zobrazen':'Nezobrazen';?>">&nbsp;</span></td>
							<td><span class="detail"><a href="<?= $this->url(array('id'=>$this->consumptions[$i]['id']),'admin_options_consumptions-edit');?>" title="Upravit"></a></span></td>
							<td><span class="delete"><a href="<?= $this->url(array('id'=>$this->consumptions[$i]['id']),'admin_options_consumptions-del');?>" title="Smazat"></a></span></td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyl přidán žádný způsob odběru</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>