<div class="block">

	<h1 class="plus">Přidat adresu</h1>
	<h3>Informace o adrese</h3>
	Fakturační a dodací údaje nelze po jejich vložení dodatečně měnit. Je to z důvodu jejich provázanosti s informačním systémem, evidencí objednávek a přehledu doručení zboží.
	Proto prosím před uložením údajů vždy zkontrolujte jejich správnost.
	Můžete si vytvořit několik fakturačních i dodacích adres a ty při objednávání zboží střídat.
	<br /><br />
	Položky označené * je nutné vyplnit. Údaje prosím vyplňujte s diakritikou !
	<?= $this->form;?>

</div>