<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_sitemap');?>">Mapa stránek</a>  &#62; </li>
	  <li>Výrobci</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Výrobci</li>
	  <li class="line" style="width: 665px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_sitemap_manufacturers-add');?>"><span class="add-item"></span>Přidat výrobce</a>
		<div class="clearfix"></div>
		<table id="tree_table">
			<thead>
				<tr>
					<th>Výrobce</th>
					<th>Menu</th>
					<th>URL</th>
					<th class="width-30">&nbsp;</th>
					<th class="width-30">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->manufacturers){?>
					<?php for ($i = 0; $i < count($this->manufacturers); $i++) {?>
						<tr>
							<td><?= $this->manufacturers[$i]['title']?></td>
							<td><?= $this->manufacturers[$i]['title_menu']?></td>
							<td><?= $this->manufacturers[$i]['title_url']?></td>
							<td><span class="detail"><a href="<?= $this->url(array('id'=>$this->manufacturers[$i]['id']),'admin_sitemap_manufacturers-edit');?>" title="Upravit"></a></span></td>
							<td><span class="delete"><a href="<?= $this->url(array('id'=>$this->manufacturers[$i]['id']),'admin_sitemap_manufacturers-del');?>" title="Smazat"></a></span></td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyla přidána žádná kategorie zboží</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>