<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_elements');?>">Prvky stránek</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'newsletter_admin_index');?>">Novinky emailem</a> &#62; </li>
	  <li>Editovat novinku</li>
	</ul>
</nav>
<section class="newsletter">
	<div class="clearfix"></div>
	<nav id="form-tab-menu">
		<ul>
		  <li id="newsletters" class="first active">Editovat novinku</li>
		  <li id="send" class="last">Rozeslat</li>
		  <li class="line" style="width: 554px;"></li>
		</ul>
	</nav>
	<div id="form-tab-box">
		<div id="tab1">
			<?= $this->form;?>
		</div>
		<div id="tab2">
			<?= $this->formSend;?>
		</div>
	</div>
</section>