[production]
; INDEX *******************************************************************************************
routes.eshop_index_index.route = "/"
routes.eshop_index_index.defaults.module = eshop
routes.eshop_index_index.defaults.controller = index
routes.eshop_index_index.defaults.action = index

routes.eshop_index_category.route = "/kategorie/:category/:page"
routes.eshop_index_category.defaults.module = eshop
routes.eshop_index_category.defaults.controller = index
routes.eshop_index_category.defaults.action = category
routes.eshop_index_category.defaults.page = 1
routes.eshop_index_category.reqs.page = "\d+"

routes.eshop_index_product.route = "/kategorie/:category/zbozi/:product"
routes.eshop_index_product.defaults.module = eshop
routes.eshop_index_product.defaults.controller = index
routes.eshop_index_product.defaults.action = product

routes.eshop_index_contacts.route = "/kontakty"
routes.eshop_index_contacts.defaults.module = eshop
routes.eshop_index_contacts.defaults.controller = index
routes.eshop_index_contacts.defaults.action = contacts

routes.eshop_index_sitemap.route = "/mapa-stranek"
routes.eshop_index_sitemap.defaults.module = eshop
routes.eshop_index_sitemap.defaults.controller = index
routes.eshop_index_sitemap.defaults.action = sitemap

routes.eshop_index_recommend.route = "/doporucujeme/:page"
routes.eshop_index_recommend.defaults.module = eshop
routes.eshop_index_recommend.defaults.controller = index
routes.eshop_index_recommend.defaults.action = recommend
routes.eshop_index_recommend.defaults.page = 1
routes.eshop_index_recommend.reqs.page = "\d+"

routes.eshop_index_recommend-product.route = "/doporucujeme/zbozi/:product"
routes.eshop_index_recommend-product.defaults.module = eshop
routes.eshop_index_recommend-product.defaults.controller = index
routes.eshop_index_recommend-product.defaults.action = recommend-product

routes.eshop_index_news.route = "/novinky/:page"
routes.eshop_index_news.defaults.module = eshop
routes.eshop_index_news.defaults.controller = index
routes.eshop_index_news.defaults.action = news
routes.eshop_index_news.defaults.page = 1
routes.eshop_index_news.reqs.page = "\d+"

routes.eshop_index_news-product.route = "/novinky/zbozi/:product"
routes.eshop_index_news-product.defaults.module = eshop
routes.eshop_index_news-product.defaults.controller = index
routes.eshop_index_news-product.defaults.action = news-product

; *************************************************************************************************
; MANUFACTURERS ***********************************************************************************
routes.eshop_manufacturers_index.route = "/vyrobci/:page"
routes.eshop_manufacturers_index.defaults.module = eshop
routes.eshop_manufacturers_index.defaults.controller = manufacturers
routes.eshop_manufacturers_index.defaults.action = index
routes.eshop_manufacturers_index.defaults.page = 1
routes.eshop_manufacturers_index.reqs.page = "\d+"

routes.eshop_manufacturers_manufactury.route = "/vyrobce/:manufactury/:page"
routes.eshop_manufacturers_manufactury.defaults.module = eshop
routes.eshop_manufacturers_manufactury.defaults.controller = manufacturers
routes.eshop_manufacturers_manufactury.defaults.action = manufactury
routes.eshop_manufacturers_manufactury.defaults.page = 1
routes.eshop_manufacturers_manufactury.reqs.page = "\d+"

routes.eshop_manufacturers_product.route = "/vyrobce/:manufactury/zbozi/:product"
routes.eshop_manufacturers_product.defaults.module = eshop
routes.eshop_manufacturers_product.defaults.controller = manufacturers
routes.eshop_manufacturers_product.defaults.action = product
; *************************************************************************************************
; SEARCH ******************************************************************************************
routes.eshop_index_search.route = "/vyhledat/:page"
routes.eshop_index_search.defaults.module = eshop
routes.eshop_index_search.defaults.controller = index
routes.eshop_index_search.defaults.action = search
routes.eshop_index_search.defaults.page = 1
routes.eshop_index_search.reqs.page = "\d+"



; *************************************************************************************************


routes.eshop_index_pages.route = "/clanky/:page"
routes.eshop_index_pages.defaults.module = eshop
routes.eshop_index_pages.defaults.controller = index
routes.eshop_index_pages.defaults.action = pages