<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_sitemap');?>">Mapa stránek</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_sitemap_pages_index');?>">Články</a>  &#62; </li>
	  <li>Přidat článek</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active">Přidat článek</li>
	  <li id="settings" class="last disable">Nastavení</li>
	  <li class="line" style="width: 567px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formPages;?>
	</div>
</div>