<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_sitemap');?>">Mapa stránek</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_sitemap_pages_index');?>">Články</a>  &#62; </li>
	  <li>Smazat článek</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="users" class="first active last">Smazat článek</li>
	  <li class="line" style="width: 624px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<h2 class="text-center">Opravdu chcete smazat článek "<?= $this->page;?>"?</h2>
		<?= $this->form;?>
	</div>
</div>