<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_sitemap');?>">Mapa stránek</a>  &#62; </li>
	  <li>Články</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="pages" class="first active last">Články</li>
	  <li class="line" style="width: 668px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_sitemap_pages_add');?>"><span class="add-item"></span>Přidat článek</a>
		<div class="clearfix"></div>
		<table>
			<thead>
				<tr>
					<th>Články</th>
					<th class="width-80">Zobrazen</th>
					<th class="width-40">&nbsp;</th>
					<th class="width-40">&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->pages){?>
					<?php for ($i = 0; $i < count($this->pages); $i++) {?>
						<tr>
							<td><?= $this->pages[$i]['title']?></td>
							<td><span class="<?= ($this->pages[$i]['show'])?'check':'uncheck';?>" title="<?= ($this->pages[$i]['show'])?'Zobrazen':'Nezobrazen';?>">&nbsp;</span></td>
							<td><span class="detail"><a href="<?= $this->url(array('id'=>$this->pages[$i]['id']),'admin_sitemap_pages_edit');?>" title="Upravit"></a></span></td>
							<td><span class="delete"><a href="<?= $this->url(array('id'=>$this->pages[$i]['id']),'admin_sitemap_pages_del');?>" title="Smazat"></a></span></td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyl přidán žádný článek</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>