<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_sitemap');?>">Mapa stránek</a>  &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_sitemap_categories-index');?>">Kategorie zboží</a>  &#62; </li>
	  <li>Upravit kategorii zboží</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="categories" class="first active last">Upravit kategorii zboží</li>
	  <li class="line" style="width: 580px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<?= $this->formCategories;?>
	</div>
</div>