<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li>Nastavení</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active last">Nastavení</li>
	  <li class="line" style="width: 652px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<nav>
			<ul>
				<li><a href="<?= $this->url(array(),'admin_options_countries-index');?>">Přehled zemí</a></li>
				<li><a href="<?= $this->url(array(),'admin_options_payments-index');?>">Způsob plateb</a></li>
				<li><a href="<?= $this->url(array(),'admin_options_consumptions-index');?>">Způsob odběru</a></li>
				<li><a href="<?= $this->url(array(),'admin_options_options-eshop');?>">Nastavení eshopu</a></li>
				<li><a href="<?= $this->url(array(),'admin_options_options-about');?>">Informace o produktu</a></li>
			</ul>
		</nav>
	</div>
</div>