<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li>Objednávky</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active last">Objednávky</li>
	  <li class="line" style="width: 639px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<nav>
			<ul>
				<li><a href="<?= $this->url(array(),'admin_orders_orders-index');?>">Přehled objednávek</a></li>
			</ul>
		</nav>
	</div>
</div>