<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li>Mapa stránek</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active last">Mapa stránek</li>
	  <li class="line" style="width: 631px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<nav>
			<ul>
				<li><a href="<?= $this->url(array(),'admin_sitemap_pages_home-page');?>">Titulní stránka</a></li>
				<li><a href="<?= $this->url(array(),'admin_sitemap_pages_index');?>">Články</a></li>
				<li><a href="<?= $this->url(array(),'admin_sitemap_categories-index');?>">Kategorie zboží</a></li>
				<li><a href="<?= $this->url(array(),'admin_sitemap_manufacturers-index');?>">Výrobci</a></li>
			</ul>
		</nav>
	</div>
</div>