<nav class="sitemap">
	<ul>
	  <li><a href="<?= $this->url(array(),'admin_index_index');?>">Úvod</a> &#62; </li>
	  <li><a href="<?= $this->url(array(),'admin_index_products');?>">Zboží</a>  &#62; </li>
	  <li>Přehled dostupností</li>
	</ul>
</nav>
<div class="clearfix"></div>
<nav id="form-tab-menu">
	<ul>
	  <li id="product" class="first active last">Přehled dostupnosti</li>
	  <li class="line" style="width: 596px;"></li>
	</ul>
</nav>
<div id="form-tab-box">
	<div id="tab1">
		<a href="<?= $this->url(array(),'admin_products_availability-add');?>"><span class="add-item"></span>Přidat dostupnost</a>
		<div class="clearfix"></div>
		<table>
			<thead>
				<tr>
					<th>Přehled dostupnosti</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
			<tbody>
				<?php if ($this->availability){?>
					<?php for ($i = 0; $i < count($this->availability); $i++) {?>
						<tr>
							<td><?= $this->availability[$i]['title']?></td>
							<td style="width: 20px;">
								<span class="detail">
									<a href="<?= $this->url(array('id'=>$this->availability[$i]['id']),'admin_products_availability-edit');?>"
									   title="Upravit"></a>
								</span>
							</td>
							<td style="width: 20px;">
								<span class="delete">
									<a href="<?= $this->url(array('id'=>$this->availability[$i]['id']),'admin_products_availability-del');?>"
									   title="Smazat"></a>
								</span>
							</td>
						</tr>
					<?php }?>
				<?php }else{?>
					<tr>
						<td>Zatím nebyla přidána žádná dostupnost</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
</div>